workflow:
  auto_cancel:
    on_new_commit: interruptible

default:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - until docker info; do sleep 1; done
    - env
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test
  - release
  - deploy
  - pages

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/logilib:latest
build:
  stage: build
  script:
    - docker pull $CONTAINER_RELEASE_IMAGE || true
    - docker build --pull -t $CI_REGISTRY_IMAGE/logilib:`echo $CI_COMMIT_BRANCH$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME | sed 's/\///g'` .
    - docker push $CI_REGISTRY_IMAGE/logilib:`echo $CI_COMMIT_BRANCH$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME | sed 's/\///g'`
  only:
    - merge_requests
    - master
  interruptible: true
test:
  stage: test
  script:
    - docker pull $CI_REGISTRY_IMAGE/logilib:`echo $CI_COMMIT_BRANCH$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME | sed 's/\///g'`
    - docker run $CI_REGISTRY_IMAGE/logilib:`echo $CI_COMMIT_BRANCH$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME | sed 's/\///g'`
  only:
    - merge_requests
    - master
  interruptible: true
release-image:
  stage: release
  script:
    - docker pull $CI_REGISTRY_IMAGE/logilib:`echo $CI_COMMIT_BRANCH$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME | sed 's/\///g'`
    - docker tag $CI_REGISTRY_IMAGE/logilib:`echo $CI_COMMIT_BRANCH$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME | sed 's/\///g'` $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

pages:
  stage: pages
  image: python:3.11
  before_script: []
  services: []
  script:
    - pip install mkdocs mkdocs-material
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  only:
    - master
