
#include "Vgate_buf_1.h"
#include "Vgate_not_1.h"

#include "Vgate_and_2.h"
#include "Vgate_nand_2.h"
#include "Vgate_or_2.h"
#include "Vgate_nor_2.h"
#include "Vgate_xor_2.h"
#include "Vgate_xnor_2.h"

#include "Vgate_and_3.h"
#include "Vgate_nand_3.h"
#include "Vgate_or_3.h"
#include "Vgate_nor_3.h"
#include "Vgate_xor_3.h"
#include "Vgate_xnor_3.h"

#include "Vgate_and_4.h"
#include "Vgate_nand_4.h"
#include "Vgate_or_4.h"
#include "Vgate_nor_4.h"
#include "Vgate_xor_4.h"
#include "Vgate_xnor_4.h"

#include "Vgate_and_5.h"
#include "Vgate_nand_5.h"
#include "Vgate_or_5.h"
#include "Vgate_nor_5.h"
#include "Vgate_xor_5.h"
#include "Vgate_xnor_5.h"

#include "Vgate_and_6.h"
#include "Vgate_nand_6.h"
#include "Vgate_or_6.h"
#include "Vgate_nor_6.h"
#include "Vgate_xor_6.h"
#include "Vgate_xnor_6.h"

#include "Vgate_and_7.h"
#include "Vgate_nand_7.h"
#include "Vgate_or_7.h"
#include "Vgate_nor_7.h"
#include "Vgate_xor_7.h"
#include "Vgate_xnor_7.h"

#include "Vgate_and_8.h"
#include "Vgate_nand_8.h"
#include "Vgate_or_8.h"
#include "Vgate_nor_8.h"
#include "Vgate_xor_8.h"
#include "Vgate_xnor_8.h"

// #include "Vgate_and_9.h"
// #include "Vgate_nand_9.h"
// #include "Vgate_or_9.h"
// #include "Vgate_nor_9.h"
// #include "Vgate_xor_9.h"
// #include "Vgate_xnor_9.h"

// #include "Vgate_and_10.h"
// #include "Vgate_nand_10.h"
// #include "Vgate_or_10.h"
// #include "Vgate_nor_10.h"
// #include "Vgate_xor_10.h"
// #include "Vgate_xnor_10.h"

// #include "Vgate_and_11.h"
// #include "Vgate_nand_11.h"
// #include "Vgate_or_11.h"
// #include "Vgate_nor_11.h"
// #include "Vgate_xor_11.h"
// #include "Vgate_xnor_11.h"

// #include "Vgate_and_12.h"
// #include "Vgate_nand_12.h"
// #include "Vgate_or_12.h"
// #include "Vgate_nor_12.h"
// #include "Vgate_xor_12.h"
// #include "Vgate_xnor_12.h"

// #include "Vgate_and_13.h"
// #include "Vgate_nand_13.h"
// #include "Vgate_or_13.h"
// #include "Vgate_nor_13.h"
// #include "Vgate_xor_13.h"
// #include "Vgate_xnor_13.h"

// #include "Vgate_and_14.h"
// #include "Vgate_nand_14.h"
// #include "Vgate_or_14.h"
// #include "Vgate_nor_14.h"
// #include "Vgate_xor_14.h"
// #include "Vgate_xnor_14.h"

// #include "Vgate_and_15.h"
// #include "Vgate_nand_15.h"
// #include "Vgate_or_15.h"
// #include "Vgate_nor_15.h"
// #include "Vgate_xor_15.h"
// #include "Vgate_xnor_15.h"

// #include "Vgate_and_16.h"
// #include "Vgate_nand_16.h"
// #include "Vgate_or_16.h"
// #include "Vgate_nor_16.h"
// #include "Vgate_xor_16.h"
// #include "Vgate_xnor_16.h"

// #include "Vgate_and_17.h"
// #include "Vgate_nand_17.h"
// #include "Vgate_or_17.h"
// #include "Vgate_nor_17.h"
// #include "Vgate_xor_17.h"
// #include "Vgate_xnor_17.h"

// #include "Vgate_and_18.h"
// #include "Vgate_nand_18.h"
// #include "Vgate_or_18.h"
// #include "Vgate_nor_18.h"
// #include "Vgate_xor_18.h"
// #include "Vgate_xnor_18.h"

// #include "Vgate_and_19.h"
// #include "Vgate_nand_19.h"
// #include "Vgate_or_19.h"
// #include "Vgate_nor_19.h"
// #include "Vgate_xor_19.h"
// #include "Vgate_xnor_19.h"

// #include "Vgate_and_20.h"
// #include "Vgate_nand_20.h"
// #include "Vgate_or_20.h"
// #include "Vgate_nor_20.h"
// #include "Vgate_xor_20.h"
// #include "Vgate_xnor_20.h"

// #include "Vgate_and_21.h"
// #include "Vgate_nand_21.h"
// #include "Vgate_or_21.h"
// #include "Vgate_nor_21.h"
// #include "Vgate_xor_21.h"
// #include "Vgate_xnor_21.h"

// #include "Vgate_and_22.h"
// #include "Vgate_nand_22.h"
// #include "Vgate_or_22.h"
// #include "Vgate_nor_22.h"
// #include "Vgate_xor_22.h"
// #include "Vgate_xnor_22.h"

// #include "Vgate_and_23.h"
// #include "Vgate_nand_23.h"
// #include "Vgate_or_23.h"
// #include "Vgate_nor_23.h"
// #include "Vgate_xor_23.h"
// #include "Vgate_xnor_23.h"

// #include "Vgate_and_24.h"
// #include "Vgate_nand_24.h"
// #include "Vgate_or_24.h"
// #include "Vgate_nor_24.h"
// #include "Vgate_xor_24.h"
// #include "Vgate_xnor_24.h"

// #include "Vgate_and_25.h"
// #include "Vgate_nand_25.h"
// #include "Vgate_or_25.h"
// #include "Vgate_nor_25.h"
// #include "Vgate_xor_25.h"
// #include "Vgate_xnor_25.h"

// #include "Vgate_and_26.h"
// #include "Vgate_nand_26.h"
// #include "Vgate_or_26.h"
// #include "Vgate_nor_26.h"
// #include "Vgate_xor_26.h"
// #include "Vgate_xnor_26.h"

// #include "Vgate_and_27.h"
// #include "Vgate_nand_27.h"
// #include "Vgate_or_27.h"
// #include "Vgate_nor_27.h"
// #include "Vgate_xor_27.h"
// #include "Vgate_xnor_27.h"

// #include "Vgate_and_28.h"
// #include "Vgate_nand_28.h"
// #include "Vgate_or_28.h"
// #include "Vgate_nor_28.h"
// #include "Vgate_xor_28.h"
// #include "Vgate_xnor_28.h"

// #include "Vgate_and_29.h"
// #include "Vgate_nand_29.h"
// #include "Vgate_or_29.h"
// #include "Vgate_nor_29.h"
// #include "Vgate_xor_29.h"
// #include "Vgate_xnor_29.h"

// #include "Vgate_and_30.h"
// #include "Vgate_nand_30.h"
// #include "Vgate_or_30.h"
// #include "Vgate_nor_30.h"
// #include "Vgate_xor_30.h"
// #include "Vgate_xnor_30.h"

// #include "Vgate_and_31.h"
// #include "Vgate_nand_31.h"
// #include "Vgate_or_31.h"
// #include "Vgate_nor_31.h"
// #include "Vgate_xor_31.h"
// #include "Vgate_xnor_31.h"

// #include "Vgate_and_32.h"
// #include "Vgate_nand_32.h"
// #include "Vgate_or_32.h"
// #include "Vgate_nor_32.h"
// #include "Vgate_xor_32.h"
// #include "Vgate_xnor_32.h"

// #include "Vgate_and_33.h"
// #include "Vgate_nand_33.h"
// #include "Vgate_or_33.h"
// #include "Vgate_nor_33.h"
// #include "Vgate_xor_33.h"
// #include "Vgate_xnor_33.h"

// #include "Vgate_and_34.h"
// #include "Vgate_nand_34.h"
// #include "Vgate_or_34.h"
// #include "Vgate_nor_34.h"
// #include "Vgate_xor_34.h"
// #include "Vgate_xnor_34.h"

// #include "Vgate_and_35.h"
// #include "Vgate_nand_35.h"
// #include "Vgate_or_35.h"
// #include "Vgate_nor_35.h"
// #include "Vgate_xor_35.h"
// #include "Vgate_xnor_35.h"

// #include "Vgate_and_36.h"
// #include "Vgate_nand_36.h"
// #include "Vgate_or_36.h"
// #include "Vgate_nor_36.h"
// #include "Vgate_xor_36.h"
// #include "Vgate_xnor_36.h"

// #include "Vgate_and_37.h"
// #include "Vgate_nand_37.h"
// #include "Vgate_or_37.h"
// #include "Vgate_nor_37.h"
// #include "Vgate_xor_37.h"
// #include "Vgate_xnor_37.h"

// #include "Vgate_and_38.h"
// #include "Vgate_nand_38.h"
// #include "Vgate_or_38.h"
// #include "Vgate_nor_38.h"
// #include "Vgate_xor_38.h"
// #include "Vgate_xnor_38.h"

// #include "Vgate_and_39.h"
// #include "Vgate_nand_39.h"
// #include "Vgate_or_39.h"
// #include "Vgate_nor_39.h"
// #include "Vgate_xor_39.h"
// #include "Vgate_xnor_39.h"

// #include "Vgate_and_40.h"
// #include "Vgate_nand_40.h"
// #include "Vgate_or_40.h"
// #include "Vgate_nor_40.h"
// #include "Vgate_xor_40.h"
// #include "Vgate_xnor_40.h"

// #include "Vgate_and_41.h"
// #include "Vgate_nand_41.h"
// #include "Vgate_or_41.h"
// #include "Vgate_nor_41.h"
// #include "Vgate_xor_41.h"
// #include "Vgate_xnor_41.h"

// #include "Vgate_and_42.h"
// #include "Vgate_nand_42.h"
// #include "Vgate_or_42.h"
// #include "Vgate_nor_42.h"
// #include "Vgate_xor_42.h"
// #include "Vgate_xnor_42.h"

// #include "Vgate_and_43.h"
// #include "Vgate_nand_43.h"
// #include "Vgate_or_43.h"
// #include "Vgate_nor_43.h"
// #include "Vgate_xor_43.h"
// #include "Vgate_xnor_43.h"

// #include "Vgate_and_44.h"
// #include "Vgate_nand_44.h"
// #include "Vgate_or_44.h"
// #include "Vgate_nor_44.h"
// #include "Vgate_xor_44.h"
// #include "Vgate_xnor_44.h"

// #include "Vgate_and_45.h"
// #include "Vgate_nand_45.h"
// #include "Vgate_or_45.h"
// #include "Vgate_nor_45.h"
// #include "Vgate_xor_45.h"
// #include "Vgate_xnor_45.h"

// #include "Vgate_and_46.h"
// #include "Vgate_nand_46.h"
// #include "Vgate_or_46.h"
// #include "Vgate_nor_46.h"
// #include "Vgate_xor_46.h"
// #include "Vgate_xnor_46.h"

// #include "Vgate_and_47.h"
// #include "Vgate_nand_47.h"
// #include "Vgate_or_47.h"
// #include "Vgate_nor_47.h"
// #include "Vgate_xor_47.h"
// #include "Vgate_xnor_47.h"

// #include "Vgate_and_48.h"
// #include "Vgate_nand_48.h"
// #include "Vgate_or_48.h"
// #include "Vgate_nor_48.h"
// #include "Vgate_xor_48.h"
// #include "Vgate_xnor_48.h"

// #include "Vgate_and_49.h"
// #include "Vgate_nand_49.h"
// #include "Vgate_or_49.h"
// #include "Vgate_nor_49.h"
// #include "Vgate_xor_49.h"
// #include "Vgate_xnor_49.h"

// #include "Vgate_and_50.h"
// #include "Vgate_nand_50.h"
// #include "Vgate_or_50.h"
// #include "Vgate_nor_50.h"
// #include "Vgate_xor_50.h"
// #include "Vgate_xnor_50.h"

// #include "Vgate_and_51.h"
// #include "Vgate_nand_51.h"
// #include "Vgate_or_51.h"
// #include "Vgate_nor_51.h"
// #include "Vgate_xor_51.h"
// #include "Vgate_xnor_51.h"

// #include "Vgate_and_52.h"
// #include "Vgate_nand_52.h"
// #include "Vgate_or_52.h"
// #include "Vgate_nor_52.h"
// #include "Vgate_xor_52.h"
// #include "Vgate_xnor_52.h"

// #include "Vgate_and_53.h"
// #include "Vgate_nand_53.h"
// #include "Vgate_or_53.h"
// #include "Vgate_nor_53.h"
// #include "Vgate_xor_53.h"
// #include "Vgate_xnor_53.h"

// #include "Vgate_and_54.h"
// #include "Vgate_nand_54.h"
// #include "Vgate_or_54.h"
// #include "Vgate_nor_54.h"
// #include "Vgate_xor_54.h"
// #include "Vgate_xnor_54.h"

// #include "Vgate_and_55.h"
// #include "Vgate_nand_55.h"
// #include "Vgate_or_55.h"
// #include "Vgate_nor_55.h"
// #include "Vgate_xor_55.h"
// #include "Vgate_xnor_55.h"

// #include "Vgate_and_56.h"
// #include "Vgate_nand_56.h"
// #include "Vgate_or_56.h"
// #include "Vgate_nor_56.h"
// #include "Vgate_xor_56.h"
// #include "Vgate_xnor_56.h"

// #include "Vgate_and_57.h"
// #include "Vgate_nand_57.h"
// #include "Vgate_or_57.h"
// #include "Vgate_nor_57.h"
// #include "Vgate_xor_57.h"
// #include "Vgate_xnor_57.h"

// #include "Vgate_and_58.h"
// #include "Vgate_nand_58.h"
// #include "Vgate_or_58.h"
// #include "Vgate_nor_58.h"
// #include "Vgate_xor_58.h"
// #include "Vgate_xnor_58.h"

// #include "Vgate_and_59.h"
// #include "Vgate_nand_59.h"
// #include "Vgate_or_59.h"
// #include "Vgate_nor_59.h"
// #include "Vgate_xor_59.h"
// #include "Vgate_xnor_59.h"

// #include "Vgate_and_60.h"
// #include "Vgate_nand_60.h"
// #include "Vgate_or_60.h"
// #include "Vgate_nor_60.h"
// #include "Vgate_xor_60.h"
// #include "Vgate_xnor_60.h"

// #include "Vgate_and_61.h"
// #include "Vgate_nand_61.h"
// #include "Vgate_or_61.h"
// #include "Vgate_nor_61.h"
// #include "Vgate_xor_61.h"
// #include "Vgate_xnor_61.h"

// #include "Vgate_and_62.h"
// #include "Vgate_nand_62.h"
// #include "Vgate_or_62.h"
// #include "Vgate_nor_62.h"
// #include "Vgate_xor_62.h"
// #include "Vgate_xnor_62.h"

// #include "Vgate_and_63.h"
// #include "Vgate_nand_63.h"
// #include "Vgate_or_63.h"
// #include "Vgate_nor_63.h"
// #include "Vgate_xor_63.h"
// #include "Vgate_xnor_63.h"

// #include "Vgate_and_64.h"
// #include "Vgate_nand_64.h"
// #include "Vgate_or_64.h"
// #include "Vgate_nor_64.h"
// #include "Vgate_xor_64.h"
// #include "Vgate_xnor_64.h"
