/* Generated by Yosys 0.21+10 (git sha1 a21745052, gcc 13.1.6 -fPIC -Os) */

(* dynports =  1  *)
(* hdlname = "\\multi_and" *)
(* src = "src/multi_and.v:1.1-26.10" *)
module \$paramod\multi_and\SIZE=s32'00000000000000000000000000000001 (out, e1);
  (* src = "src/multi_and.v:6.21-6.23" *)
  input e1;
  wire e1;
  (* src = "src/multi_and.v:7.16-7.19" *)
  output out;
  wire out;
  assign out = e1;
endmodule

(* dynports =  1  *)
(* hdlname = "\\multi_and" *)
(* src = "src/multi_and.v:1.1-26.10" *)
module \$paramod\multi_and\SIZE=s32'00000000000000000000000000000010 (out, e1);
  (* src = "src/multi_and.v:6.21-6.23" *)
  input [1:0] e1;
  wire [1:0] e1;
  (* src = "src/multi_and.v:7.16-7.19" *)
  output out;
  wire out;
  assign out = e1[1] & e1[0];
endmodule

(* dynports =  1  *)
(* hdlname = "\\multi_nand" *)
(* src = "src/multi_nand.v:1.1-26.10" *)
module \$paramod\multi_nand\SIZE=s32'00000000000000000000000000000001 (out, e1);
  (* src = "src/multi_nand.v:9.22-9.24" *)
  wire W3;
  (* src = "src/multi_nand.v:6.21-6.23" *)
  input e1;
  wire e1;
  (* src = "src/multi_nand.v:7.16-7.19" *)
  output out;
  wire out;
  assign W3 = 1'hx;
  assign e1 = 1'hx;
  assign out = 1'hx;
endmodule

(* dynports =  1  *)
(* hdlname = "\\multi_nand" *)
(* src = "src/multi_nand.v:1.1-26.10" *)
module \$paramod\multi_nand\SIZE=s32'00000000000000000000000000000010 (out, e1);
  (* src = "src/multi_nand.v:9.22-9.24" *)
  wire W3;
  (* src = "src/multi_nand.v:6.21-6.23" *)
  input [1:0] e1;
  wire [1:0] e1;
  (* src = "src/multi_nand.v:7.16-7.19" *)
  output out;
  wire out;
  assign W3 = 1'hx;
  assign out = 1'hx;
endmodule

(* dynports =  1  *)
(* hdlname = "\\multi_nor" *)
(* src = "src/multi_nor.v:1.1-26.10" *)
module \$paramod\multi_nor\SIZE=s32'00000000000000000000000000000001 (out, e1);
  (* src = "src/multi_nor.v:6.21-6.23" *)
  input e1;
  wire e1;
  (* src = "src/multi_nor.v:7.16-7.19" *)
  output out;
  wire out;
  assign out = e1;
endmodule

(* dynports =  1  *)
(* hdlname = "\\multi_nor" *)
(* src = "src/multi_nor.v:1.1-26.10" *)
module \$paramod\multi_nor\SIZE=s32'00000000000000000000000000000010 (out, e1);
  (* src = "src/multi_nor.v:6.21-6.23" *)
  input [1:0] e1;
  wire [1:0] e1;
  (* src = "src/multi_nor.v:7.16-7.19" *)
  output out;
  wire out;
  assign out = ~(e1[1] | e1[0]);
endmodule

(* dynports =  1  *)
(* src = "src/multi_and.v:1.1-26.10" *)
module multi_and(out, e1);
  (* src = "src/multi_and.v:9.14-9.16" *)
  wire W1;
  (* src = "src/multi_and.v:9.18-9.20" *)
  wire W2;
  (* src = "src/multi_and.v:6.21-6.23" *)
  input [2:0] e1;
  wire [2:0] e1;
  (* src = "src/multi_and.v:7.16-7.19" *)
  output out;
  wire out;
  assign out = W2 & W1;
  (* src = "src/multi_and.v:22.25-22.62" *)
  \$paramod\multi_and\SIZE=s32'00000000000000000000000000000010  \genblk1.genblk1.genblk1.recall1  (
    .e1(e1[2:1]),
    .out(W1)
  );
  (* src = "src/multi_and.v:23.25-23.52" *)
  \$paramod\multi_and\SIZE=s32'00000000000000000000000000000001  \genblk1.genblk1.genblk1.recall2  (
    .e1(e1[0]),
    .out(W2)
  );
endmodule

(* dynports =  1  *)
(* src = "src/multi_nand.v:1.1-26.10" *)
module multi_nand(out, e1);
  (* src = "src/multi_nand.v:9.14-9.16" *)
  wire W1;
  (* src = "src/multi_nand.v:9.18-9.20" *)
  wire W2;
  (* src = "src/multi_nand.v:6.21-6.23" *)
  input [2:0] e1;
  wire [2:0] e1;
  (* src = "src/multi_nand.v:7.16-7.19" *)
  output out;
  wire out;
  assign out = ~(W1 & W2);
  (* src = "src/multi_nand.v:22.26-22.63" *)
  \$paramod\multi_nand\SIZE=s32'00000000000000000000000000000010  \genblk1.genblk1.genblk1.recall1  (
    .e1(e1[2:1]),
    .out(W1)
  );
  (* src = "src/multi_nand.v:23.26-23.53" *)
  \$paramod\multi_nand\SIZE=s32'00000000000000000000000000000001  \genblk1.genblk1.genblk1.recall2  (
    .e1(e1[0]),
    .out(W2)
  );
endmodule

(* dynports =  1  *)
(* src = "src/multi_nor.v:1.1-26.10" *)
module multi_nor(out, e1);
  (* src = "src/multi_nor.v:9.14-9.16" *)
  wire W1;
  (* src = "src/multi_nor.v:9.18-9.20" *)
  wire W2;
  (* src = "src/multi_nor.v:6.21-6.23" *)
  input [2:0] e1;
  wire [2:0] e1;
  (* src = "src/multi_nor.v:7.16-7.19" *)
  output out;
  wire out;
  assign out = ~(W2 | W1);
  (* src = "src/multi_nor.v:22.25-22.62" *)
  \$paramod\multi_nor\SIZE=s32'00000000000000000000000000000010  \genblk1.genblk1.genblk1.recall1  (
    .e1(e1[2:1]),
    .out(W1)
  );
  (* src = "src/multi_nor.v:23.25-23.52" *)
  \$paramod\multi_nor\SIZE=s32'00000000000000000000000000000001  \genblk1.genblk1.genblk1.recall2  (
    .e1(e1[0]),
    .out(W2)
  );
endmodule
