/* Generated by Yosys 0.21+10 (git sha1 a21745052, gcc 13.1.6 -fPIC -Os) */

(* dynports =  1  *)
(* hdlname = "\\cpt_bin_recall" *)
(* src = "cpt_bin.v:22.1-41.10" *)
module \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000001 (clk, out, reset);
  (* src = "cpt_bin.v:26.12-26.15" *)
  input clk;
  wire clk;
  (* src = "cpt_bin.v:29.14-29.18" *)
  (* unused_bits = "0" *)
  wire line;
  (* src = "cpt_bin.v:27.22-27.25" *)
  output out;
  wire out;
  (* src = "cpt_bin.v:26.17-26.22" *)
  input reset;
  wire reset;
  (* src = "cpt_bin.v:0.0-0.0" *)
  wire vcc;
  (* module_not_derived = 32'd1 *)
  (* src = "cpt_bin.v:33.12-33.53" *)
  JKlatchUP \genblk1.JK_UP  (
    .clk(clk),
    .j(1'h1),
    .k(1'h1),
    .out1(out),
    .out2(line),
    .reset(reset)
  );
  assign vcc = 1'h1;
endmodule

(* dynports =  1  *)
(* hdlname = "\\cpt_bin_recall" *)
(* src = "cpt_bin.v:22.1-41.10" *)
module \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000010 (clk, out, reset);
  (* src = "cpt_bin.v:26.12-26.15" *)
  input clk;
  wire clk;
  (* src = "cpt_bin.v:29.14-29.18" *)
  wire line;
  (* src = "cpt_bin.v:27.22-27.25" *)
  output [1:0] out;
  wire [1:0] out;
  (* src = "cpt_bin.v:26.17-26.22" *)
  input reset;
  wire reset;
  (* src = "cpt_bin.v:0.0-0.0" *)
  wire vcc;
  (* module_not_derived = 32'd1 *)
  (* src = "cpt_bin.v:37.12-37.53" *)
  JKlatchUP \genblk1.genblk1.JK_UP  (
    .clk(clk),
    .j(1'h1),
    .k(1'h1),
    .out1(out[0]),
    .out2(line),
    .reset(reset)
  );
  (* src = "cpt_bin.v:38.34-38.69" *)
  \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000001  \genblk1.genblk1.recurse  (
    .clk(line),
    .out(out[1]),
    .reset(reset)
  );
  assign vcc = 1'h1;
endmodule

(* dynports =  1  *)
(* hdlname = "\\cpt_bin_recall" *)
(* src = "cpt_bin.v:22.1-41.10" *)
module \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000011 (clk, out, reset);
  (* src = "cpt_bin.v:26.12-26.15" *)
  input clk;
  wire clk;
  (* src = "cpt_bin.v:29.14-29.18" *)
  wire line;
  (* src = "cpt_bin.v:27.22-27.25" *)
  output [2:0] out;
  wire [2:0] out;
  (* src = "cpt_bin.v:26.17-26.22" *)
  input reset;
  wire reset;
  (* src = "cpt_bin.v:0.0-0.0" *)
  wire vcc;
  (* module_not_derived = 32'd1 *)
  (* src = "cpt_bin.v:37.12-37.53" *)
  JKlatchUP \genblk1.genblk1.JK_UP  (
    .clk(clk),
    .j(1'h1),
    .k(1'h1),
    .out1(out[0]),
    .out2(line),
    .reset(reset)
  );
  (* src = "cpt_bin.v:38.34-38.69" *)
  \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000010  \genblk1.genblk1.recurse  (
    .clk(line),
    .out(out[2:1]),
    .reset(reset)
  );
  assign vcc = 1'h1;
endmodule

(* dynports =  1  *)
(* hdlname = "\\cpt_bin_recall" *)
(* src = "cpt_bin.v:22.1-41.10" *)
module \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000100 (clk, out, reset);
  (* src = "cpt_bin.v:26.12-26.15" *)
  input clk;
  wire clk;
  (* src = "cpt_bin.v:29.14-29.18" *)
  wire line;
  (* src = "cpt_bin.v:27.22-27.25" *)
  output [3:0] out;
  wire [3:0] out;
  (* src = "cpt_bin.v:26.17-26.22" *)
  input reset;
  wire reset;
  (* src = "cpt_bin.v:0.0-0.0" *)
  wire vcc;
  (* module_not_derived = 32'd1 *)
  (* src = "cpt_bin.v:37.12-37.53" *)
  JKlatchUP \genblk1.genblk1.JK_UP  (
    .clk(clk),
    .j(1'h1),
    .k(1'h1),
    .out1(out[0]),
    .out2(line),
    .reset(reset)
  );
  (* src = "cpt_bin.v:38.34-38.69" *)
  \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000011  \genblk1.genblk1.recurse  (
    .clk(line),
    .out(out[3:1]),
    .reset(reset)
  );
  assign vcc = 1'h1;
endmodule

(* dynports =  1  *)
(* hdlname = "\\cpt_bin_recall" *)
(* src = "cpt_bin.v:22.1-41.10" *)
module \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000101 (clk, out, reset);
  (* src = "cpt_bin.v:26.12-26.15" *)
  input clk;
  wire clk;
  (* src = "cpt_bin.v:29.14-29.18" *)
  wire line;
  (* src = "cpt_bin.v:27.22-27.25" *)
  output [4:0] out;
  wire [4:0] out;
  (* src = "cpt_bin.v:26.17-26.22" *)
  input reset;
  wire reset;
  (* src = "cpt_bin.v:0.0-0.0" *)
  wire vcc;
  (* module_not_derived = 32'd1 *)
  (* src = "cpt_bin.v:37.12-37.53" *)
  JKlatchUP \genblk1.genblk1.JK_UP  (
    .clk(clk),
    .j(1'h1),
    .k(1'h1),
    .out1(out[0]),
    .out2(line),
    .reset(reset)
  );
  (* src = "cpt_bin.v:38.34-38.69" *)
  \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000100  \genblk1.genblk1.recurse  (
    .clk(line),
    .out(out[4:1]),
    .reset(reset)
  );
  assign vcc = 1'h1;
endmodule

(* dynports =  1  *)
(* hdlname = "\\cpt_bin_recall" *)
(* src = "cpt_bin.v:22.1-41.10" *)
module \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000110 (clk, out, reset);
  (* src = "cpt_bin.v:26.12-26.15" *)
  input clk;
  wire clk;
  (* src = "cpt_bin.v:29.14-29.18" *)
  wire line;
  (* src = "cpt_bin.v:27.22-27.25" *)
  output [5:0] out;
  wire [5:0] out;
  (* src = "cpt_bin.v:26.17-26.22" *)
  input reset;
  wire reset;
  (* src = "cpt_bin.v:0.0-0.0" *)
  wire vcc;
  (* module_not_derived = 32'd1 *)
  (* src = "cpt_bin.v:37.12-37.53" *)
  JKlatchUP \genblk1.genblk1.JK_UP  (
    .clk(clk),
    .j(1'h1),
    .k(1'h1),
    .out1(out[0]),
    .out2(line),
    .reset(reset)
  );
  (* src = "cpt_bin.v:38.34-38.69" *)
  \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000101  \genblk1.genblk1.recurse  (
    .clk(line),
    .out(out[5:1]),
    .reset(reset)
  );
  assign vcc = 1'h1;
endmodule

(* dynports =  1  *)
(* hdlname = "\\cpt_bin_recall" *)
(* src = "cpt_bin.v:22.1-41.10" *)
module \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000111 (clk, out, reset);
  (* src = "cpt_bin.v:26.12-26.15" *)
  input clk;
  wire clk;
  (* src = "cpt_bin.v:29.14-29.18" *)
  wire line;
  (* src = "cpt_bin.v:27.22-27.25" *)
  output [6:0] out;
  wire [6:0] out;
  (* src = "cpt_bin.v:26.17-26.22" *)
  input reset;
  wire reset;
  (* src = "cpt_bin.v:0.0-0.0" *)
  wire vcc;
  (* module_not_derived = 32'd1 *)
  (* src = "cpt_bin.v:37.12-37.53" *)
  JKlatchUP \genblk1.genblk1.JK_UP  (
    .clk(clk),
    .j(1'h1),
    .k(1'h1),
    .out1(out[0]),
    .out2(line),
    .reset(reset)
  );
  (* src = "cpt_bin.v:38.34-38.69" *)
  \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000110  \genblk1.genblk1.recurse  (
    .clk(line),
    .out(out[6:1]),
    .reset(reset)
  );
  assign vcc = 1'h1;
endmodule

(* src = "../../memory/src/JKlatch.v:27.1-52.10" *)
module JKlatchDown(j, k, clk, reset, out1, out2);
  (* src = "../../memory/src/JKlatch.v:28.16-28.19" *)
  input clk;
  wire clk;
  (* src = "../../memory/src/JKlatch.v:28.10-28.11" *)
  input j;
  wire j;
  (* src = "../../memory/src/JKlatch.v:28.13-28.14" *)
  input k;
  wire k;
  (* src = "../../memory/src/JKlatch.v:31.15-31.19" *)
  wire [7:0] line;
  (* src = "../../memory/src/JKlatch.v:33.15-33.25" *)
  wire [1:0] line_reset;
  (* src = "../../memory/src/JKlatch.v:29.11-29.15" *)
  output out1;
  wire out1;
  (* src = "../../memory/src/JKlatch.v:29.17-29.21" *)
  output out2;
  wire out2;
  (* src = "../../memory/src/JKlatch.v:28.21-28.26" *)
  input reset;
  wire reset;
  (* src = "../../memory/src/JKlatch.v:32.15-32.22" *)
  wire unclock;
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:39.20-39.57" *)
  multigate_nand3 nand0 (
    .in1(j),
    .in2(line_reset[1]),
    .in3(clk),
    .out(line[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:41.14-41.46" *)
  gate_nand nand1 (
    .e1(line[1]),
    .e2(unclock),
    .s(line[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:42.14-42.52" *)
  gate_nand nand2 (
    .e1(line[2]),
    .e2(line_reset[1]),
    .s(out1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:45.20-45.51" *)
  multigate_nand3 nand3 (
    .in1(k),
    .in2(out1),
    .in3(clk),
    .out(line[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:47.14-47.46" *)
  gate_nand nand4 (
    .e1(line[5]),
    .e2(unclock),
    .s(line[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:48.14-48.46" *)
  gate_nand nand5 (
    .e1(line[6]),
    .e2(line[4]),
    .s(out2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:40.14-40.57" *)
  gate_nand nand_down0 (
    .e1(line[0]),
    .e2(line_reset[0]),
    .s(line[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:46.14-46.51" *)
  gate_nand nand_down1 (
    .e1(line[4]),
    .e2(line[1]),
    .s(line[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:37.13-37.31" *)
  gate_not not0 (
    .e1(clk),
    .s(unclock)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:35.12-35.52" *)
  gate_or or_reset0 (
    .e1(reset),
    .e2(line[5]),
    .s(line_reset[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:36.12-36.52" *)
  gate_or or_reset1 (
    .e1(reset),
    .e2(out2),
    .s(line_reset[1])
  );
  assign { line[7], line[3] } = { out2, out1 };
endmodule

(* src = "../../memory/src/JKlatch.v:1.1-25.10" *)
module JKlatchUP(j, k, clk, reset, out1, out2);
  (* src = "../../memory/src/JKlatch.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "../../memory/src/JKlatch.v:2.10-2.11" *)
  input j;
  wire j;
  (* src = "../../memory/src/JKlatch.v:2.13-2.14" *)
  input k;
  wire k;
  (* src = "../../memory/src/JKlatch.v:5.15-5.19" *)
  wire [7:0] line;
  (* src = "../../memory/src/JKlatch.v:7.15-7.25" *)
  wire [1:0] line_reset;
  (* src = "../../memory/src/JKlatch.v:3.11-3.15" *)
  output out1;
  wire out1;
  (* src = "../../memory/src/JKlatch.v:3.17-3.21" *)
  output out2;
  wire out2;
  (* src = "../../memory/src/JKlatch.v:2.21-2.26" *)
  input reset;
  wire reset;
  (* src = "../../memory/src/JKlatch.v:6.15-6.22" *)
  wire unclock;
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:13.20-13.61" *)
  multigate_nand3 nand0 (
    .in1(j),
    .in2(line_reset[1]),
    .in3(unclock),
    .out(line[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:15.14-15.42" *)
  gate_nand nand1 (
    .e1(line[1]),
    .e2(clk),
    .s(line[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:16.14-16.52" *)
  gate_nand nand2 (
    .e1(line[2]),
    .e2(line_reset[1]),
    .s(out1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:19.20-19.55" *)
  multigate_nand3 nand3 (
    .in1(k),
    .in2(out1),
    .in3(unclock),
    .out(line[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:21.14-21.42" *)
  gate_nand nand4 (
    .e1(line[5]),
    .e2(clk),
    .s(line[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:22.14-22.46" *)
  gate_nand nand5 (
    .e1(line[6]),
    .e2(out1),
    .s(out2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:14.13-14.50" *)
  gate_nor nor0 (
    .e1(line[0]),
    .e2(line_reset[0]),
    .s(line[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:20.13-20.44" *)
  gate_nor nor1 (
    .e1(line[4]),
    .e2(line[1]),
    .s(line[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:12.13-12.31" *)
  gate_not not0 (
    .e1(clk),
    .s(unclock)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:9.12-9.52" *)
  gate_or or_reset0 (
    .e1(reset),
    .e2(line[5]),
    .s(line_reset[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../memory/src/JKlatch.v:10.12-10.52" *)
  gate_or or_reset1 (
    .e1(reset),
    .e2(out2),
    .s(line_reset[1])
  );
  assign { line[7], line[3] } = { out2, out1 };
endmodule

(* dynports =  1  *)
(* src = "cpt_bin.v:1.1-20.10" *)
module cpt_bin(activate, clk, reset, out);
  (* src = "cpt_bin.v:3.10-3.18" *)
  input activate;
  wire activate;
  (* src = "cpt_bin.v:3.20-3.23" *)
  input clk;
  wire clk;
  (* src = "cpt_bin.v:0.0-0.0" *)
  wire ignore;
  wire [1:0] line;
  (* src = "cpt_bin.v:4.22-4.25" *)
  output [7:0] out;
  wire [7:0] out;
  (* src = "cpt_bin.v:3.25-3.30" *)
  input reset;
  wire reset;
  (* src = "cpt_bin.v:0.0-0.0" *)
  wire vcc;
  assign line[0] = clk & activate;
  (* module_not_derived = 32'd1 *)
  (* src = "cpt_bin.v:13.12-13.58" *)
  JKlatchUP \genblk1.JK0  (
    .clk(line[0]),
    .j(1'h1),
    .k(1'h1),
    .out1(out[0]),
    .out2(line[1]),
    .reset(reset)
  );
  (* src = "cpt_bin.v:16.39-16.74" *)
  \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000111  \genblk1.genblk1.inst  (
    .clk(line[1]),
    .out(out[7:1]),
    .reset(reset)
  );
  assign ignore = 1'h0;
  assign vcc = 1'h1;
endmodule

(* dynports =  1  *)
(* src = "cpt_bin.v:22.1-41.10" *)
module cpt_bin_recall(clk, out, reset);
  (* src = "cpt_bin.v:26.12-26.15" *)
  input clk;
  wire clk;
  (* src = "cpt_bin.v:29.14-29.18" *)
  wire line;
  (* src = "cpt_bin.v:27.22-27.25" *)
  output [7:0] out;
  wire [7:0] out;
  (* src = "cpt_bin.v:26.17-26.22" *)
  input reset;
  wire reset;
  (* src = "cpt_bin.v:0.0-0.0" *)
  wire vcc;
  (* module_not_derived = 32'd1 *)
  (* src = "cpt_bin.v:37.12-37.53" *)
  JKlatchUP \genblk1.genblk1.JK_UP  (
    .clk(clk),
    .j(1'h1),
    .k(1'h1),
    .out1(out[0]),
    .out2(line),
    .reset(reset)
  );
  (* src = "cpt_bin.v:38.34-38.69" *)
  \$paramod\cpt_bin_recall\SIZE=s32'00000000000000000000000000000111  \genblk1.genblk1.recurse  (
    .clk(line),
    .out(out[7:1]),
    .reset(reset)
  );
  assign vcc = 1'h1;
endmodule

(* src = "../../primitive/src/gate.v:15.1-21.10" *)
module gate_and(e1, e2, s);
  (* src = "../../primitive/src/gate.v:16.10-16.12" *)
  input e1;
  wire e1;
  (* src = "../../primitive/src/gate.v:17.10-17.12" *)
  input e2;
  wire e2;
  (* src = "../../primitive/src/gate.v:18.11-18.12" *)
  output s;
  wire s;
  assign s = e2 & e1;
endmodule

(* src = "../../primitive/src/multigate.v:1.1-5.10" *)
module gate_and3(a, b, c, s);
  wire _0_;
  (* src = "../../primitive/src/multigate.v:2.10-2.11" *)
  input a;
  wire a;
  (* src = "../../primitive/src/multigate.v:2.12-2.13" *)
  input b;
  wire b;
  (* src = "../../primitive/src/multigate.v:2.14-2.15" *)
  input c;
  wire c;
  (* src = "../../primitive/src/multigate.v:3.11-3.12" *)
  output s;
  wire s;
  assign _0_ = ~(b & a);
  assign s = c & ~(_0_);
endmodule

(* src = "../../primitive/src/multigate.v:7.1-11.10" *)
module gate_and4(a, b, c, d, s);
  wire _0_;
  wire _1_;
  (* src = "../../primitive/src/multigate.v:8.10-8.11" *)
  input a;
  wire a;
  (* src = "../../primitive/src/multigate.v:8.12-8.13" *)
  input b;
  wire b;
  (* src = "../../primitive/src/multigate.v:8.14-8.15" *)
  input c;
  wire c;
  (* src = "../../primitive/src/multigate.v:8.16-8.17" *)
  input d;
  wire d;
  (* src = "../../primitive/src/multigate.v:9.11-9.12" *)
  output s;
  wire s;
  assign _0_ = b & a;
  assign _1_ = ~(_0_ & c);
  assign s = d & ~(_1_);
endmodule

(* src = "../../primitive/src/multigate.v:13.1-17.10" *)
module gate_and5(a, b, c, d, e, s);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "../../primitive/src/multigate.v:14.10-14.11" *)
  input a;
  wire a;
  (* src = "../../primitive/src/multigate.v:14.12-14.13" *)
  input b;
  wire b;
  (* src = "../../primitive/src/multigate.v:14.14-14.15" *)
  input c;
  wire c;
  (* src = "../../primitive/src/multigate.v:14.16-14.17" *)
  input d;
  wire d;
  (* src = "../../primitive/src/multigate.v:14.18-14.19" *)
  input e;
  wire e;
  (* src = "../../primitive/src/multigate.v:15.16-15.17" *)
  output s;
  wire s;
  assign _0_ = b & a;
  assign _1_ = _0_ & c;
  assign _2_ = ~(_1_ & d);
  assign s = e & ~(_2_);
endmodule

(* src = "../../primitive/src/gate.v:1.1-6.10" *)
module gate_buf(e1, s);
  (* src = "../../primitive/src/gate.v:2.10-2.12" *)
  input e1;
  wire e1;
  (* src = "../../primitive/src/gate.v:3.11-3.12" *)
  output s;
  wire s;
  assign s = e1;
endmodule

(* src = "../../primitive/src/gate.v:44.1-49.10" *)
module gate_nand(e1, e2, s);
  (* src = "../../primitive/src/gate.v:45.10-45.12" *)
  input e1;
  wire e1;
  (* src = "../../primitive/src/gate.v:45.14-45.16" *)
  input e2;
  wire e2;
  (* src = "../../primitive/src/gate.v:46.11-46.12" *)
  output s;
  wire s;
  assign s = ~(e2 & e1);
endmodule

(* src = "../../primitive/src/gate.v:51.1-56.10" *)
module gate_nor(e1, e2, s);
  (* src = "../../primitive/src/gate.v:52.10-52.12" *)
  input e1;
  wire e1;
  (* src = "../../primitive/src/gate.v:52.14-52.16" *)
  input e2;
  wire e2;
  (* src = "../../primitive/src/gate.v:53.11-53.12" *)
  output s;
  wire s;
  assign s = ~(e2 | e1);
endmodule

(* src = "../../primitive/src/gate.v:8.1-13.10" *)
module gate_not(e1, s);
  (* src = "../../primitive/src/gate.v:9.10-9.12" *)
  input e1;
  wire e1;
  (* src = "../../primitive/src/gate.v:10.11-10.12" *)
  output s;
  wire s;
  assign s = ~e1;
endmodule

(* src = "../../primitive/src/gate.v:23.1-28.10" *)
module gate_or(e1, e2, s);
  (* src = "../../primitive/src/gate.v:24.10-24.12" *)
  input e1;
  wire e1;
  (* src = "../../primitive/src/gate.v:24.14-24.16" *)
  input e2;
  wire e2;
  (* src = "../../primitive/src/gate.v:25.11-25.12" *)
  output s;
  wire s;
  assign s = e2 | e1;
endmodule

(* src = "../../primitive/src/multigate.v:26.1-30.10" *)
module gate_or4(a, b, c, d, s);
  wire _0_;
  wire _1_;
  (* src = "../../primitive/src/multigate.v:27.10-27.11" *)
  input a;
  wire a;
  (* src = "../../primitive/src/multigate.v:27.13-27.14" *)
  input b;
  wire b;
  (* src = "../../primitive/src/multigate.v:27.16-27.17" *)
  input c;
  wire c;
  (* src = "../../primitive/src/multigate.v:27.19-27.20" *)
  input d;
  wire d;
  (* src = "../../primitive/src/multigate.v:28.11-28.12" *)
  output s;
  wire s;
  assign _0_ = b | a;
  assign _1_ = _0_ | c;
  assign s = _1_ | d;
endmodule

(* src = "../../primitive/src/gate.v:37.1-42.10" *)
module gate_xnor(e1, e2, s);
  (* src = "../../primitive/src/gate.v:38.10-38.12" *)
  input e1;
  wire e1;
  (* src = "../../primitive/src/gate.v:38.14-38.16" *)
  input e2;
  wire e2;
  (* src = "../../primitive/src/gate.v:39.11-39.12" *)
  output s;
  wire s;
  assign s = ~(e2 ^ e1);
endmodule

(* src = "../../primitive/src/gate.v:30.1-35.10" *)
module gate_xor(e1, e2, s);
  (* src = "../../primitive/src/gate.v:31.10-31.12" *)
  input e1;
  wire e1;
  (* src = "../../primitive/src/gate.v:31.14-31.16" *)
  input e2;
  wire e2;
  (* src = "../../primitive/src/gate.v:32.11-32.12" *)
  output s;
  wire s;
  assign s = e2 ^ e1;
endmodule

(* src = "../../primitive/src/multigate.v:19.1-24.10" *)
module multigate_and8(bus, s);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "../../primitive/src/multigate.v:20.16-20.19" *)
  input [7:0] bus;
  wire [7:0] bus;
  (* src = "../../primitive/src/multigate.v:21.16-21.17" *)
  output s;
  wire s;
  assign _00_ = bus[1] & bus[0];
  assign _01_ = _00_ & bus[2];
  assign _02_ = _01_ & bus[3];
  assign _03_ = _02_ & bus[4];
  assign _04_ = _03_ & bus[5];
  assign _05_ = ~(_04_ & bus[6]);
  assign s = bus[7] & ~(_05_);
endmodule

(* src = "../../primitive/src/multigate.v:48.1-56.10" *)
module multigate_nand3(in1, in2, in3, out);
  (* src = "../../primitive/src/multigate.v:49.10-49.13" *)
  input in1;
  wire in1;
  (* src = "../../primitive/src/multigate.v:49.15-49.18" *)
  input in2;
  wire in2;
  (* src = "../../primitive/src/multigate.v:49.20-49.23" *)
  input in3;
  wire in3;
  (* src = "../../primitive/src/multigate.v:51.15-51.19" *)
  wire [1:0] line;
  (* src = "../../primitive/src/multigate.v:50.11-50.14" *)
  output out;
  wire out;
  (* module_not_derived = 32'd1 *)
  (* src = "../../primitive/src/multigate.v:53.14-53.38" *)
  gate_nand nand0 (
    .e1(in1),
    .e2(in2),
    .s(line[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../primitive/src/multigate.v:54.14-54.38" *)
  gate_nand nand1 (
    .e1(in2),
    .e2(in3),
    .s(line[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../primitive/src/multigate.v:55.12-55.38" *)
  gate_or or0 (
    .e1(line[0]),
    .e2(line[1]),
    .s(out)
  );
endmodule

(* src = "../../primitive/src/multigate.v:39.1-46.10" *)
module multigate_or16(bus, s);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "../../primitive/src/multigate.v:40.17-40.20" *)
  input [15:0] bus;
  wire [15:0] bus;
  (* src = "../../primitive/src/multigate.v:41.12-41.13" *)
  output s;
  wire s;
  assign _00_ = bus[1] | bus[0];
  assign _01_ = _00_ | bus[2];
  assign _02_ = _01_ | bus[3];
  assign _03_ = _02_ | bus[4];
  assign _04_ = _03_ | bus[5];
  assign _05_ = _04_ | bus[6];
  assign _06_ = _05_ | bus[7];
  assign _07_ = _06_ | bus[8];
  assign _08_ = _07_ | bus[9];
  assign _09_ = _08_ | bus[10];
  assign _10_ = _09_ | bus[11];
  assign _11_ = _10_ | bus[12];
  assign _12_ = _11_ | bus[13];
  assign _13_ = _12_ | bus[14];
  assign s = _13_ | bus[15];
endmodule

(* src = "../../primitive/src/multigate.v:32.1-37.10" *)
module multigate_or8(bus, s);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "../../primitive/src/multigate.v:33.16-33.19" *)
  input [7:0] bus;
  wire [7:0] bus;
  (* src = "../../primitive/src/multigate.v:34.12-34.13" *)
  output s;
  wire s;
  assign _00_ = bus[1] | bus[0];
  assign _01_ = _00_ | bus[2];
  assign _02_ = _01_ | bus[3];
  assign _03_ = _02_ | bus[4];
  assign _04_ = _03_ | bus[5];
  assign _05_ = _04_ | bus[6];
  assign s = _05_ | bus[7];
endmodule
